services:
  - type: web
    name: zagros-checker
    env: node
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
